### ISSUE TITLE
ip2location.IP2Locationrecord has no field or method ProxyType

### ISSUE THREAD

**Issue by GarryGaller** [ip2location/ip2location-go#11]
Why does the library not include the proxytype field in the ip2locationrecord structure?

**Comment by ip2location** [comment]
This Go Package is meant for reading IP2Location BIN files. For reading the IP2Proxy BIN files, you need to use the [IP2Proxy Go Package](https://github.com/ip2location/ip2proxy-go).

**Comment by GarryGaller** [comment]
Thanks.
