### ISSUE TITLE
Reduce GC pressure

### ISSUE THREAD

**Issue by calvinxiao** [ip2location/ip2location-go#14]
Hi 

I added benchmark to my local branch, found these GC performance issues

1. in `readuint32()` method, `binary.Read` ~~uses reflection and~~ will allocate more memory then `binary.LittleEndian.Uint32()` , here are the benchmarks

```
# err = binary.Read(buf, binary.LittleEndian, &retval)
BenchmarkGetAll1-16        14084             84946 ns/op           10161 B/op        696 allocs/op

# using retval = binary.LittleEndian.Uint32(data[:])
BenchmarkGetAllOld-16              15841             75894 ns/op            5569 B/op        450 allocs/op
```

2. `math/big` provides arbitrary precision, which allocates more memory, we could use a `Uint128` library such as `lukechampine.com/uint128` to store ipv4 and ipv6 as Uint128, here is the benchmark using `Uint128`

```
BenchmarkGetAllOld-16              17890             67029 ns/op            1776 B/op        276 allocs/op
```

Total performance improvement is 27%, and allocs/op decreases 60%.

Can I send a PR? If so I will need to add some tests, I only test it with ipv4 data.

### My local commit

1. [binary.LittleEndian.Uint32](https://github.com/calvinxiao/ip2location-go/blob/performance-cache/ip2location.go#L257)
2. [Uint128](https://github.com/calvinxiao/ip2location-go/commit/4813081034ef73fc594c6eb929291e0f8fe151ab)

**Comment by ip2location** [comment]
Hi,

Yes, we would be interested to see the performance improvements for both IPv4 and IPv6.

Please send us your benchmark improvement numbers for both.

You can also send us the PR once you have done your testing on IPv6.

We have one small request. We would prefer not to rely on 3rd-party packages. Can you modify your codes accordingly and still maintain the performance?

**Comment by calvinxiao** [comment]
Sure, I can do more tests on ipv6 data.

**Comment by ip2location** [comment]
Will close this issue for now. When you're ready, you can create a pull request.
