### ISSUE TITLE
Timezone is empty and EOF is always an error

### ISSUE THREAD

**Issue by TzahiFadida** [ip2location/ip2location-go#19]
Hi, using the recent documentation and a recent lite version with timezone.
I am always getting an EOF error but the data is actually there so it is a minor issue, however, the Timezone is always empty.

Thanks.

**Comment by ip2location** [comment]
Can you please show us your code? Which BIN file are you trying to read?

**Comment by TzahiFadida** [comment]
It is the same as the example code and it is go version go1.18.3 darwin/arm64 
https://lite.ip2location.com/download?id=10 or https://lite.ip2location.com/download?id=20

`package main

import (
	"fmt"
	"github.com/ip2location/ip2location-go/v9"
)

func main() {
	db, err := ip2location.OpenDB("1.BIN")

	if err != nil {
		fmt.Print(err)
		return
	}
	ip := "8.8.8.8"
	results, err := db.Get_all(ip)

	if err != nil {
		fmt.Print(err)
		return
	}

	fmt.Printf("country_short: %s\n", results.Country_short)
	fmt.Printf("country_long: %s\n", results.Country_long)
	fmt.Printf("region: %s\n", results.Region)
	fmt.Printf("city: %s\n", results.City)
	fmt.Printf("isp: %s\n", results.Isp)
	fmt.Printf("latitude: %f\n", results.Latitude)
	fmt.Printf("longitude: %f\n", results.Longitude)
	fmt.Printf("domain: %s\n", results.Domain)
	fmt.Printf("zipcode: %s\n", results.Zipcode)
	fmt.Printf("timezone: %s\n", results.Timezone)
	fmt.Printf("netspeed: %s\n", results.Netspeed)
	fmt.Printf("iddcode: %s\n", results.Iddcode)
	fmt.Printf("areacode: %s\n", results.Areacode)
	fmt.Printf("weatherstationcode: %s\n", results.Weatherstationcode)
	fmt.Printf("weatherstationname: %s\n", results.Weatherstationname)
	fmt.Printf("mcc: %s\n", results.Mcc)
	fmt.Printf("mnc: %s\n", results.Mnc)
	fmt.Printf("mobilebrand: %s\n", results.Mobilebrand)
	fmt.Printf("elevation: %f\n", results.Elevation)
	fmt.Printf("usagetype: %s\n", results.Usagetype)
	fmt.Printf("addresstype: %s\n", results.Addresstype)
	fmt.Printf("category: %s\n", results.Category)
	fmt.Printf("api version: %s\n", ip2location.Api_version())

	db.Close()
}
`
result:
EOFExiting.
a breakpoint on the results gives:
"Country_short = {string} "US"
Country_long = {string} "United States of America"
Region = {string} "California"
City = {string} "Mountain View"
Isp = {string} "This parameter is unavailable for selected data file. Please upgrade the data file."
Latitude = {float32} 37.40599
Longitude = {float32} -122.078514
Domain = {string} "This parameter is unavailable for selected data file. Please upgrade the data file."
Zipcode = {string} "94043"
Timezone = {string} ""
Netspeed = {string} "This parameter is unavailable for selected data file. Please upgrade the data file."
Iddcode = {string} "This parameter is unavailable for selected data file. Please upgrade the data file."
Areacode = {string} "This parameter is unavailable for selected data file. Please upgrade the data file."
....
..

**Comment by ip2location** [comment]
We've fixed the issue in the latest version. Please give it a try.
