### ISSUE TITLE
Idiomatic Go

### ISSUE THREAD

**Issue by pjebs** [ip2location/ip2location-go#6]
Please make this package properly follow Go convention and operate like how a Go package should.

If you need assistance, I can do it within a day for a fee: Here are my other packages: https://github.com/rocketlaunchr

Currently, I can't even with confidence know when a ip address can/cant be converted.
I can't even Open and Close the database on a (http) per-request basis.

**Comment by ip2location** [comment]
Thanks @csucu on the partial fixes, appreciated! We will review and test the fixes before the merge.

Hi @pjebs, we welcome improvements/suggestions to keep enhance the library further to benefit all GO lang users. As for an open source library, you can fork our library for the changes and send us the pull request. However, there is nothing wrong if you think that a compensation would be good for the modification, we do have "Development Fund" as stated in our library page at https://www.ip2location.com/development-libraries. Please email us at support@ip2location.com, and we can proceed from there.
